### ISSUE TITLE
Why the dependency on kotlin-gradle-plugin?

### ISSUE THREAD

**Issue by jbluntz** [dropbox/dependency-guard#32]
When I applied this plugin to one of my projects, I ran into unrelated issues in my build, which I traced to the unintentional upgrade of the kotlin-gradle-plugin.  Are the implementation dependencies on kotlin-gradle-plugin  and the kotlin BoM necessary?  I tried removing them - the tests still pass and the tasks seem to function appropriately in the sample app as well.

**Comment by handstandsam** [comment]
Good question!  I'm not sure they are needed.

https://github.com/dropbox/dependency-guard/blob/main/dependency-guard/build.gradle.kts#L64-L65
```
  implementation(platform(libs.kotlin.bom))
  implementation(libs.kotlin.plugin)
```

I'll try to remove them and see what happens.

**Comment by handstandsam** [comment]
This is now part of `0.3.0` which I just kicked off the publishing job for 👍

**Comment by jbluntz** [comment]
Thanks for the quick response!
