### ISSUE TITLE
Can I easily protect all the dependencies of all the modules in a multi-module project?

### ISSUE THREAD

**Issue by azabost** [dropbox/dependency-guard#37]
Hi.

First of all, thanks for creating this plugin. It's truly awesome 👍 

However, I'm not sure how I could apply this plugin in a more generic way to cover all the possible dependencies in the whole multi-module project. Preferably, I would like to be able to guard literally all the dependencies, including the test dependencies (`testImplementation` / `testAndroidImplementation` etc.) of all the modules.

I figured out I can declare multiple `configuration() { ... }` blocks, for example in my `app` module I have:

```kotlin
dependencyGuard {
    listOf(
        // In most cases, "XRuntime" will contain "XCompile" dependencies but not always so we check all just in case
        "stageDebugCompileClasspath",
        "stageDebugRuntimeClasspath",
        "stageDebugUnitTestCompileClasspath",
        "stageDebugUnitTestRuntimeClasspath",
        "stageDebugAndroidTestCompileClasspath",
        "stageDebugAndroidTestRuntimeClasspath"
    ).forEach {
        configuration(it) {
            artifacts = true
            modules = false
            tree = false
        }
    }
}
```

However, I'm afraid that if `app` module has a dependency on `featureX` module, and `featureX` has `testImplementation` dependency on `org.slf4j:slf4j-simple` that is **not** used by `app`, then Dependency Guard can't protect against unwanted `org.slf4j:slf4j-simple` version changes, unless I apply the plugin to `featureX` module separately.

Therefore, I'm wondering what is the easiest way to cover that case.

1. Is there any option to run the Dependency Guard against the whole project at once by configuring it once in a single place?
2. Should I just apply this plugin to all my modules? If this is the suggested solution, then I have two more issues/questions:
    1. For `m` number of modules it's going to produce at least `m` text files (or `m x n` to cover `n` configurations in each module), where most of the dependencies are going to be the same (e.g. `kotlin-stdlib`). Therefore, it would be great to merge all these files into a single one for multi-module setup.
    2. When I tried using the plugin in `allprojects` in the root `build.gradle.kts` file, I applied the plugin and immediately stumbled upon a problem with the `clean` task. I'm not sure if it's a bug within this plugin or I simply did something wrong.
        ```
        org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/azabost/projects/[redacted]/build.gradle.kts' line: 115
        Cannot add task 'clean' as a task with that name already exists.
        at org.gradle.kotlin.dsl.execution.InterpreterKt$locationAwareExceptionFor$2.invoke(Interpreter.kt:601)
        (...)
        Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'clean' as a task with that name already exists.
        at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:257)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.registerTask(DefaultTaskContainer.java:398)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.register(DefaultTaskContainer.java:375)
        at Build_gradle.<init>(build.gradle.kts:115)
        (...)
        ```

Can you advise something to cover my use case, please?

**Comment by handstandsam** [comment]
There is no way to specify dependency guard for all modules unless you did some sort of

```
rootProject.subprojects.forEach {
  // Apply Plugin
  // Configure Plugin
}
```

I think that would create more noise than signal though.

**Comment by handstandsam** [comment]
Since there was no reply in a month, I'm going to close this issue.  Please feel free to comment and we can re-open.

**Comment by azabost** [comment]
Thanks a lot for all the detailed answers.

I suppose that expecting Dependency Guard to produce a single "merged" report for all the modules was unreasonable given what you said about transitive dependencies in libraries. I can clearly see the problem now.

Judging by the drawbacks of the other solutions such as the lockfiles etc., using Dependency Guard still seems to be the most reasonable approach.

Feel free to keep this issue closed as I've got the answers I needed.
