### ISSUE TITLE
Tasks not compatible with the configuration cache

### ISSUE THREAD

**Issue by autonomousapps** [dropbox/dependency-guard#4]
First of all, this is not surprising, as dependency analysis in general is not well-supported by the configuration cache (CC). However, since I'm adding this to my project, I want an issue to refer to explain why CC has been disabled for these tasks.

I'm using the [runtime API](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#notCompatibleWithConfigurationCache-java.lang.String-) for this, available since Gradle 7.4. This looks like:
```groovy
tasks.named('dependencyGuard') {
  notCompatibleWithConfigurationCache('https://github.com/dropbox/dependency-guard/issues/4')
}
```
I'm not sure which versions of Gradle you want to support, but you might bake this in with something like
```
tasks.register(...) {
  if (GradleVersion.current() > GradleVersion.version("7.4")) {
    notCompatibleWithConfigurationCache('https://github.com/dropbox/dependency-guard/issues/4')
  }
}
```
And of course, ideally, one day, this could be compatible out of the box.

**Comment by handstandsam** [comment]
Reopening because I'm seeing issues locally when running.  Works every time when I specify `--no-configuration-cache`, but fails after the first run otherwise.

**Comment by handstandsam** [comment]
Opened [this issue for Gradle](https://github.com/gradle/gradle/issues/20765), but it looks like it's "working as intended".  It is a weird configuration that causes this scenario.
