### ISSUE TITLE
DependencyReportTask may be deprecated

### ISSUE THREAD

**Issue by fornewid** [dropbox/dependency-guard#44]
This is not an issue, just a question. :smile:

You know,
there is an issue that DependencyReportTask is not compatible with the configuration cache. (#4)
And I found [**this**](https://issuetracker.google.com/issues/235457021) while browsing the issue tracker. :eyes:

> https://issuetracker.google.com/issues/235457021
> We should just deprecate this task, it's not that useful.

I know that this open source works based on DependencyReportTask.
So I wonder if this library will still work even if DependencyReportTask is deprecated.
Any other alternatives?

**Comment by handstandsam** [comment]
That is a separate task that is in AGP. Named similarly, but different. We use a task built into Gradle. Thank you!
