### ISSUE TITLE
Update dependency-tree-diff

### ISSUE THREAD

**Issue by qwert2603** [dropbox/dependency-guard#45]
Hello!

`dependencyTreeDiff` sources are copied to this project from [dependency-tree-diff](https://github.com/JakeWharton/dependency-tree-diff) from commit `2548d3e95aa709c2c2b95ed61241a49bfadddd72` ([file's history](https://github.com/JakeWharton/dependency-tree-diff/commits/trunk/src/main/kotlin/com/jakewharton/gradle/dependencies/treeDiff.kt)).

And now there is a newer version in the original repo (commit `4e86e45bbb032535d8106aec2811399f4bce7b49`). It would be great to update sources in this repo to receive bug fixes from the original repo.

**Comment by handstandsam** [comment]
Thank you!  I wish that library was published as a JAR file as it would make it easier, but will do this as well along with your #46

**Comment by handstandsam** [comment]
Ahh!! I hadn't seen your PR. https://github.com/dropbox/dependency-guard/pull/47.  Thank you.  Will close my version and merge yours.  Thank you!

**Comment by handstandsam** [comment]
0.3.2 is publishing and contains this fix.
