### ISSUE TITLE
Fix "baseline created" message in DependencyGuardTreeDiffer

### ISSUE THREAD

**Issue by qwert2603** [dropbox/dependency-guard#46]
Hello!

When `DependencyGuardTreeDiffer` writes a tree baseline file, it prints the following message ([sources](https://github.com/dropbox/dependency-guard/blob/main/dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/utils/DependencyGuardTreeDiffer.kt#L41)):

```
"Dependency Guard Tree baseline created for : for configuration classpath."
```

But `DependencyGuardTreeDiffer` writes a tree baseline file for the given `project.path` and `configurationName`, not only for `:` and `classpath`. So it would be useful to print the correct `project.path` and `configurationName` in the output message.

Expected example of the output message:

```
"Dependency Guard Tree baseline created for :lib for configuration testCompileClasspath."
```

**Comment by handstandsam** [comment]
Ahh, so there are 2 usages of this method.
1. Using the `build environment tree`
2. Using the `project environment tree`

I must have just been testing the message for the build environment.  Good catch!

**Comment by handstandsam** [comment]
0.3.2 is publishing and contains this fix.

**Comment by qwert2603** [comment]
Thanks for the fix!

> Also, are you using this on anything open source?

Currently not. But I may try it on some of my pet projects later.

**Comment by handstandsam** [comment]
Thank you. Are you using the library for something private or at work? Just curious what kind of configuration you have. Cheers

**Comment by qwert2603** [comment]
I'm planning to use the library for a work project. I also think that `list` configuration is more useful than `tree`. And it's helpful to guard `releaseRuntimeClasspath`, `debugUnitTestRuntimeClasspath` and `debugAndroidTestRuntimeClasspath` for the app module and `classpath` confuguration for the root gradle project to get full picture of project dependencies.
